version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sch226kiyvcitY
      MYSQL_DATABASE: wordpress226
      MYSQL_USER: user226
      MYSQL_PASSWORD: Sch226kiyvcitY

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user226
      WORDPRESS_DB_PASSWORD: Sch226kiyvcitY
      WORDPRESS_DB_NAME: wordpress226
      WORDPRESS_CONFIG_EXTRA: |
        if (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
            $$_SERVER['HTTPS'] = 'on';
        }
        define('WP_HOME', 'https://' . $$_SERVER['HTTP_HOST']);
        define('WP_SITEURL', 'https://' . $$_SERVER['HTTP_HOST']);
